version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes: 
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "todo-frontend-dev"
      - "todo-backend-dev"
    ports:
      - 8080:80
    container_name: reverse-proxy
  todo-frontend-dev:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app   
    environment:
      - REACT_APP_BACKEND_URL=/api
    container_name: todo-frontend-dev
  todo-backend-dev:
    image: todo-backend-dev
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app  
    depends_on:
      - "mongo"
      - "redis"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - PORT=3001      
    container_name: todo-backend-dev
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:       
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: mongo
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis

volumes:
  mongo_data: 